### ISSUE TITLE
Create the LICENSE file

### ISSUE THREAD

**Issue by ghost** [k0kubun/twitter-auth#4]
Currently, the license for this program is not explicitly stated.
Could you please create a LICENSE file?

See also: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by k0kubun** [comment]
> Currently, the license for this program is not explicitly stated.

This is not correct https://github.com/k0kubun/twitter-auth/blob/6ef9d470e345d383bdd244e34bff439608681c5b/README.md?plain=1#L42, but I'll add a file.
