### ISSUE TITLE
Feature Request: Headless mode

### ISSUE THREAD

**Issue by ghost** [k0kubun/twitter-auth#5]
I would like to have a mode that does not automatically open the browser at runtime, but just displays the URL in the stdout.

**Comment by k0kubun** [comment]
Sounds good. Please feel free to open a pull request. I'll merge it once filed.

**Comment by ghost** [comment]
> Sounds good. Please feel free to open a pull request. I'll merge it once filed.

Hmmm, I can't write code, so that is difficult.

**Comment by k0kubun** [comment]
I don't really use this tool anymore, and thus I don't afford to spend my time on this. To avoid confusing people, let me permanently archive this repository to make it explicit. Thank you.
